micronaut:
  application:
    name: shareholdergame-facade

  server:
    port: 8081
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://dev.stockholdergame.com

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    token:
      jwt:
        enabled: true

  router:
    static-resources:
      swagger:
        enabled: true
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

  executors:
    scheduled:
      type: scheduled
      core-pool-size: 10

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/shareholdergame
    username: root
    password: 123
    driverClassName: org.mariadb.jdbc.Driver
